sudo: required
language: node_js
node_js:
- '8'
services:
- docker
before_install:
- yarn --cwd ./integration-tests install
script:
- yarn test
- yarn integration-tests
after_success:
- yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
- yarn report-coverage
before_deploy:
  - git config --local user.name "terascope-ci"
  - git config --local user.email "ci@terascope.io"
deploy:
  - provider: releases
    name: "$TRAVIS_TAG"
    prerelease: true
    api_key:
      secure: "ikJIrNiYXy2kd2WvFMvG8zkKUI5uXUVTG1OJ9E7pQPRbp5tqmCsko9AQVx+51ChWi5a25CFbkhhG6FGZoukU9i70QyZ5WuQUFmjLrdSjjCw9uVPd9G+n0CyDUaFbRTsqY4gkt0E6Zb6P3ULpex5DU55Nvn+lhRkHxYKsQSSTVEe1tF7jdvaSXruCxRVssnc/goN8x43POS9veouC5of3nvUhUX/7mo4qER7P2vhm3yh5hjbf22+seNKcxP99dTrrVO9Cm2m9B41RW3p7tdzVrZ7q8RUdmPiY/SG/Al+8W2mj9NTOTd78JH6016GK/7gdiHbFungUbz0tYYizrNP6RahaZVRtUnz0nJMYtIEe2l7q/UStV2TlGngQAummxOhmBbrh7fjfSm+uu6SnKlhghicBIR91kscNpMHeCuhHXTedNZd/VD4zZFDUqTP0yLM+5toQByK7n9zg4CBdfTlJ8cC0ikf97xxr/KE5uK7gFOpNfC1z4nW4Ir+c9k8Xf97rT+kz26JzoN+BWxHGa1DlTCwpuTWz51+cgWG9w2OtUvWz3JdRpPb7sFQtCswiS+TkHtz/r9JKKmIMDnFhx4GAJbSfFxKM/KMvDOeMrRVbI6TVuzCa1aH1oLipXz6tFOQRDPCX80HIxloWYpYr/YofpvEeYiJkRMsEgrpVDJuHpq0="
    on:
      branch: master
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      repo: terascope/teraslice
  - provider: npm
    email: peter@terascope.io
    api_key:
      secure: IbA84R9gLLdyCaMhkvqkhgeDxcIX85LLQZbY3WbWxrw7b7zrD64+NQSkV0vztYKldlGIPqW2FmuL92FYGpb2O3WLF/jVi/cttKtiUhFZ7OXF7di7882AW+GJ6ZvKaZ/Vsb3VY5D+Rdkad1xOpZsQdDWjCOFMMYkzpsL5KRin1gpV4Os5GCZ11c40lujABVktBt+jLyxXNqpI9Reh9j3+elq+jnuZnAApVAghNQUkslFgWH7C4m2dweMieytC3zMJJYX+xnAFrA6pbZIkhEIz1pgjjPuErhZGXtEBUQ0rH9fb+N6Ooq4l5LHuvLDh22gT7gTGvyBQrNpfFWEcNP7O8I3ophHG3t/6dXfudYrEJejtxYjSXnQweXLExkEZdaiCpEOA1SlZAYghPFYg1HSuEuXguiGf/vi9UC4rPuVbLm9gQO94EMK/BHFEpFDRqiHE5Mva4rzuYXUeuMtln0dkMancxh8b0alC0XaNeG9VbWAlUIvlAErczBvqD82GDo/vF06oWOzLS5eTH0dDVvgRint0fLNgofAL7WX2KO2wohS/S9tNpIiBr+L7FZLoNWIi0jhENNCse22VVOUlmPI+2AYa/p0X7TCOwQX7Ua2MRajzjxCyNsKv9e5VpRuY4Jio102aIymXucAIecx6yPGIbUW6ioSCVJ2SCt2+voHW89E=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
      repo: terascope/teraslice
