sudo: required
language: node_js
node_js:
- '8'
services:
  - docker
  - elasticsearch
env:
  global:
  # NPM_DEPLOY_TOKEN
  - secure: PJjAOuduzYG+SvtiCEYL7Tz0ZQmY1RzXLvpT7ctINIhpiFTQvT3UZ5WK/9gI6NF/FU+oW0Nm7/GhKZZArrqNu2S86bR4M1K32WNGlLU7+CblvPEOmZ8qW+HdNZvzNo+w1IH1WHAOdP1EpdRvWCyD+o2K21W/NV9sFue0o+HDh9d1TU85EodetjZQI84o3gs04/3XLmzneDhdUhFLjaYzL/tI4Kbo7h9Dqb3Twy/HgpcckUqFWzl01ZsZA56oPkXqIehsqlPvv8Tdnke8YhBO7IQ9Vm6PbsKlBZKPwzVEcUYtzGZopWkaXkfI9mVbBWOHVt2KtwnsFpnb67JaVpEl1iXeJ09unEDnyyxRoKPe/yisu+l8IChwTSAUeibWLfGRWGEpo2AvH0RrXEzRY0Wry8py5vdMdSgxqCtNy1eAoYVmjhWhutKwR4jia19aQ6C7dao2nkScREju+PRNm72tCouyaxOXxylvus1vTpOxusGxBhoq4qCof48udC91P6mSwqy+bdlO8mJ1JpS6RnVlGK0n0KJlPyijZMchElKk6RRB3AjCnU3bUCqsCP0D2j6s10YISJ0vwn2G8MyUQIClyQ2tkfyH+uddymNJ8b1ocHrcsBYFpGQ5M2WPEyjCpZdK+LMWMQ22OFSOn/P5o6qDiFhP89th9+FXgp9vqoPZ3oY=
cache: yarn
install: yarn install && yarn bootstrap
script:
  - yarn test
  - yarn test:e2e
after_success:
  - yarn lint
  - yarn coverage
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
  - stage: Release (Draft)
    script:
      - npm config set //registry.npmjs.org/:_authToken $NPM_DEPLOY_TOKEN
      - yarn publish:draft
    after_success: skip
    deploy:
      provider: releases
      name: "$TRAVIS_TAG"
      draft: true
      api_key:
        secure: "ikJIrNiYXy2kd2WvFMvG8zkKUI5uXUVTG1OJ9E7pQPRbp5tqmCsko9AQVx+51ChWi5a25CFbkhhG6FGZoukU9i70QyZ5WuQUFmjLrdSjjCw9uVPd9G+n0CyDUaFbRTsqY4gkt0E6Zb6P3ULpex5DU55Nvn+lhRkHxYKsQSSTVEe1tF7jdvaSXruCxRVssnc/goN8x43POS9veouC5of3nvUhUX/7mo4qER7P2vhm3yh5hjbf22+seNKcxP99dTrrVO9Cm2m9B41RW3p7tdzVrZ7q8RUdmPiY/SG/Al+8W2mj9NTOTd78JH6016GK/7gdiHbFungUbz0tYYizrNP6RahaZVRtUnz0nJMYtIEe2l7q/UStV2TlGngQAummxOhmBbrh7fjfSm+uu6SnKlhghicBIR91kscNpMHeCuhHXTedNZd/VD4zZFDUqTP0yLM+5toQByK7n9zg4CBdfTlJ8cC0ikf97xxr/KE5uK7gFOpNfC1z4nW4Ir+c9k8Xf97rT+kz26JzoN+BWxHGa1DlTCwpuTWz51+cgWG9w2OtUvWz3JdRpPb7sFQtCswiS+TkHtz/r9JKKmIMDnFhx4GAJbSfFxKM/KMvDOeMrRVbI6TVuzCa1aH1oLipXz6tFOQRDPCX80HIxloWYpYr/YofpvEeYiJkRMsEgrpVDJuHpq0="
  - stage: Release
    if: tag IS present AND tag =~ ^v AND branch = master
    script:
      - npm config set //registry.npmjs.org/:_authToken $NPM_DEPLOY_TOKEN
      - yarn publish:release
    after_success: skip
    deploy:
      provider: releases
      name: "$TRAVIS_TAG"
      prerelease: true
      api_key:
        secure: "ikJIrNiYXy2kd2WvFMvG8zkKUI5uXUVTG1OJ9E7pQPRbp5tqmCsko9AQVx+51ChWi5a25CFbkhhG6FGZoukU9i70QyZ5WuQUFmjLrdSjjCw9uVPd9G+n0CyDUaFbRTsqY4gkt0E6Zb6P3ULpex5DU55Nvn+lhRkHxYKsQSSTVEe1tF7jdvaSXruCxRVssnc/goN8x43POS9veouC5of3nvUhUX/7mo4qER7P2vhm3yh5hjbf22+seNKcxP99dTrrVO9Cm2m9B41RW3p7tdzVrZ7q8RUdmPiY/SG/Al+8W2mj9NTOTd78JH6016GK/7gdiHbFungUbz0tYYizrNP6RahaZVRtUnz0nJMYtIEe2l7q/UStV2TlGngQAummxOhmBbrh7fjfSm+uu6SnKlhghicBIR91kscNpMHeCuhHXTedNZd/VD4zZFDUqTP0yLM+5toQByK7n9zg4CBdfTlJ8cC0ikf97xxr/KE5uK7gFOpNfC1z4nW4Ir+c9k8Xf97rT+kz26JzoN+BWxHGa1DlTCwpuTWz51+cgWG9w2OtUvWz3JdRpPb7sFQtCswiS+TkHtz/r9JKKmIMDnFhx4GAJbSfFxKM/KMvDOeMrRVbI6TVuzCa1aH1oLipXz6tFOQRDPCX80HIxloWYpYr/YofpvEeYiJkRMsEgrpVDJuHpq0="
