sudo: required
language: node_js
node_js:
- '8'
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
  - elasticsearch
cache:
  yarn: true
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn test:e2e
jobs:
  include:
    - stage: Run All Package Tests and Report Coverage
      if: tag IS blank
      script:
        - yarn test
      after_script:
        - yarn coverage
        - bash <(curl -s https://codecov.io/bash)
    - stage: Intergration Tests
      if: tag IS blank AND branch != master AND type = pull_request
      script:
        - yarn test:e2e
    - stage: Lint All Packages
      if: tag IS blank AND type = 'pull_request'
      script:
        - yarn lint
    - stage: Publish Packages
      if: tag IS blank AND branch = master AND type != pull_request
      script:
        - npm config set //registry.npmjs.org/:_authToken $NPM_DEPLOY_TOKEN
        - lerna publish --yes --canary=pre --skip-git
    - stage: Release Teraslice
      if: tag IS blank AND branch = master AND type != pull_request
      before_install:
        - yarn global add publish-release
      script:
        - npm config set //registry.npmjs.org/:_authToken $NPM_DEPLOY_TOKEN
        - export TERASLICE_VERSION="v$(node -pe "require('./packages/teraslice/package.json).version")"
        - echo "releasing $TERASLICE_VERSION..."
        - publish-release \
          --owner terascope \
          --token "$GITHUB_DEPLOY_TOKEN" \
          --skipIfPublished \
          --prerelease \
          --tag "$(TERASLICE_VERSION)"
        - lerna publish --yes from-git