apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
      app: elasticsearch
      nodeType: master
spec:
  replicas: 1
  selector:
      matchLabels:
          app: elasticsearch
          nodeType: master
  template:
    metadata:
      labels:
        app: elasticsearch
        nodeType: master
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:5.6.10
        ports:
        - containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
      app: elasticsearch
      nodeType: master
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30200  # the external port teraslice can be accessed on
  type: NodePort
