version: 2.0

# Aliases to avoid code duplication
aliases:
  - &restore-cache
    name: Restore yarn package cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}
      - yarn-packages

  - &save-cache
    name: Save yarn package cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &yarn-install
    name: Install node_modules
    command: yarn --no-progress --frozen-lockfile

  - &yarn-setup
    name: Link & build packages
    command: yarn setup

  - &elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - discovery.type: single-node
      - xpack.security.enabled: false
      - xpack.ml.enabled: false
      - xpack.watcher.enabled: false

jobs:
  setup_code:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install
      - save-cache: *save-cache
      - run: *yarn-setup

  test_packages:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
      - *elasticsearch-service
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install
      - save-cache: *save-cache
      - run: *yarn-setup
      - run:
          name: Waiting for elasticsearch...
          command: ./scripts/wait-for-it.sh localhost:9200 --timeout=60 --strict
      - run:
          name: Run tests
          command: ./scripts/run-tests.sh
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash)

  lint_and_benchmark:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install
      - save-cache: *save-cache
      - run: *yarn-setup
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run benchmarks
          command: yarn benchmark

  e2e_tests:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install
      - save-cache: *save-cache
      - run: *yarn-setup
      - run:
          name: Install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      # configure job to execute remote docker commands
      - setup_remote_docker
      - run:
          name: Run End-to-End Tests
          command: |
            cd e2e
            yarn test:ci

      # FIXME add the actual test

# Workflows enables mutltiple jobs to run in parallel
workflows:
  version: 2
  # FIXME add scheduled jobs
  build-and-deploy:
    jobs:
      - setup_code
      - test_packages:
          requires:
            - setup_code
      - lint_and_benchmark:
          requires:
            - setup_code
      - e2e_tests:
          requires:
            - setup_code
      # FIXME add deploy
