version: 2.0

# Aliases to avoid code duplication
aliases:
  - &restore-cache
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}
      - yarn-packages

  - &save-cache
    name: Save Yarn Package Cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      - network.host: '0.0.0.0'
      - http.port: 9200
      - transport.tcp.port: 9300
      - discovery.type: single-node
      - xpack.security.enabled: false
      - xpack.ml.enabled: false
      - xpack.watcher.enabled: false
      - bootstrap.memory_lock: true

jobs:
  setup_code:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run: yarn setup

  test_packages:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
      - *elasticsearch-service
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run: yarn setup
      - run:
          name: Waiting for elasticsearch...
          command: ./scripts/wait-for-it.sh localhost:9200 --timeout=60 --strict
      - run:
          name: Run all package tests
          command: ./scripts/run-test.sh
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash)

  lint_and_benchmark:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run: yarn setup
      - run:
          name: Lint all packages
          command: yarn lint
      - run:
          name: Run the benchmarks
          command: yarn bencmark

  e2e_tests:
    working_directory: ~/teraslice
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run: yarn setup
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      # configure job to execute remote docker commands
      - setup_remote_docker

      # FIXME add the actual test

# Workflows enables mutltiple jobs to run in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup_code
      - test_packages:
          requires:
            - setup_code
      - lint_and_benchmark:
          requires:
            - setup_code
      - e2e_tests:
          requires:
            - setup_code
