version: '2.4'
services:
    teraslice-master:
        image: terascope/teraslice:e2e
        ports:
            - '45678:45678'
        scale: 1
        restart: 'on-failure'
        stop_grace_period: 30s
        environment:
            - TERAFOUNDATION_CONFIG=/app/config/teraslice-master.json
            - NODE_OPTIONS=--max-old-space-size=256
        volumes:
            - teraslice-assets:/app/assets
            - ./logs:/app/logs:cached
            - ./autoload:/app/autoload:ro
            - ./.config:/app/config:ro
    teraslice-worker:
        image: terascope/teraslice:e2e
        scale: 2
        restart: 'on-failure'
        stop_grace_period: 30s
        environment:
            - TERAFOUNDATION_CONFIG=/app/config/teraslice-worker.json
            - NODE_OPTIONS=--max-old-space-size=256
        volumes:
            - teraslice-assets:/app/assets
            - ./logs:/app/logs:cached
            - ./autoload:/app/autoload:ro
            - ./.config:/app/config:ro

volumes:
    teraslice-assets:
        driver_opts:
            type: tmpfs
            device: tmpfs
